Extend github workflows with check to make sure requirements.txt is up to date

diff --git a/.github/workflows/main-build-and-publish.yml b/.github/workflows/main-build-and-publish.yml
--- a/.github/workflows/main-build-and-publish.yml
+++ b/.github/workflows/main-build-and-publish.yml
@@ -27,10 +27,27 @@ jobs:
           source venv/bin/activate
           pip install -r requirements.txt
 
+      - name: Check requirements.txt is up to date
+        run: |
+          source venv/bin/activate
+          pip install .[all]
+          pip uninstall -y qless-with-throttles
+          pip freeze > requirements.txt
+          git diff --quiet
+          if [ ! $? -eq 0 ]; then
+            echo "pip freeze caused file changes, failing!"
+            exit 1
+          fi
+
       - name: Check style
         run: |
           source venv/bin/activate
           make style
+          git diff --quiet
+          if [ ! $? -eq 0 ]; then
+            echo "make style caused file changes, failing!"
+            exit 1
+          fi
 
       - name: Run tests and build package
         run: |
